[package]
name = "whispr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
cpal = "0.15"
whisper-rs = "0.12"
hound = "3"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
home = "=0.5.5"

 
